### ISSUE TITLE
question on neovim c++ setup

### ISSUE THREAD

**Issue by ron0studios** [jubnzv/jubnzv.github.io#1]
Hi there!
I was reading and following your post here (https://idie.ru/posts/vim-modern-cpp/) for setting up neovim in c++.
So far everything is working fine, this is by far the most relevant post for setting up vimspector I've found, thank you!
however, I cannot find a way of installing "testrunner" for your vimspector.json file. What exactly is it, and how do I get it to work?
Thank you very much!

**Comment by jubnzv** [comment]
Hi @ron0studios,

I am glad that someone still reads my article :)
I'll check the current `vimspector` settings and update the article as soon as I have some time, in a few days.

**Comment by jubnzv** [comment]
It seems, that `testrunner` was deprecated and removed from `vscode-cpptools`. We should use `OpenDebugAD7` instead.

I tried it and everything works fine, but there is one problem. You should specify the absolute path to `OpenDebugAD7`. This means, you should go to your `plugged` directory (the default is `~/.local/share/nvim/plugged` on Linux) and use the following command to get the path:
```bash
find . -name 'OpenDebugAD7' | xargs readlink -f
```

This will give you an absolute path to the binary. You should use it in the `.vimspector.json`, for example:
```json
{
  "configurations": {
    "Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "program": "/home/jubnzv/.local/share/nvim/plugged/vimspector/gadgets/linux/download/vscode-cpptools/1.9.8/root/extension/debugAdapters/bin/OpenDebugAD7",
        "externalConsole": true
      }
    }
  }
}
```

It seems like an ad-hoc solution, but I'm not sure how to get rid of the specification of the absolute path. I asked a question about it here: https://github.com/puremourning/vimspector/discussions/597

**Comment by jubnzv** [comment]
Here is the correct config:
```json
{
  "configurations": {
    "Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "program": "${gadgetDir}/vscode-cpptools/debugAdapters/bin/OpenDebugAD7",
        "externalConsole": true
      }
    }
  }
}
```

I updated the article as well.

@ron0studios please check that everything works now.

**Comment by ron0studios** [comment]
Georgiy,
   Thank you very much for this - the config seems to be working now
perfectly!
Many thanks,
Rudrrayan Manna
